### ISSUE TITLE
Script alternatives

### ISSUE THREAD

**Issue by pixeltester** [idlesauce/ps4-5-eboot-dlc-patcher#3]
Hello, thank you for making this available. I would just like to ask if there's any possibility of creating a version of the script that could run independently or through a FOSS alternative like ghidra, in order to be more accessible?

**Comment by idlesauce** [comment]
I thought about porting to ghidra, i could even make it headless and completely self contained which would be cool, but seems like a lot of work, and unfortunately right now i cant commit the time required for this.
